metrics:
  wal_directory: /var/lib/agent/wal
  global:
    scrape_interval: 30s
    external_labels:
      cluster: kind
  configs:
  - name: default
    remote_write:
    - url: http://prometheus-server.prometheus.svc.cluster.local/api/v1/write
      basic_auth:
        username: prometheus
        password: prometheus
      send_exemplars: true
    scrape_configs:
    - job_name: kubernetes-pods
      honor_labels: true
      honor_timestamps: true
      scrape_interval: 30s
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: http
      follow_redirects: true
      enable_http2: true
      relabel_configs:
      - source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_scrape
        separator: ;
        regex: "true"
        replacement: $1
        action: keep
      - source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_scrape_slow
        separator: ;
        regex: "true"
        replacement: $1
        action: drop
      - source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_scheme
        separator: ;
        regex: (https?)
        target_label: __scheme__
        replacement: $1
        action: replace
      - source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_path
        separator: ;
        regex: (.+)
        target_label: __metrics_path__
        replacement: $1
        action: replace
      - source_labels:
        - __address__
        - __meta_kubernetes_pod_annotation_prometheus_io_port
        separator: ;
        regex: (.+?)(?::\d+)?;(\d+)
        target_label: __address__
        replacement: $1:$2
        action: replace
      - separator: ;
        regex: __meta_kubernetes_pod_annotation_prometheus_io_param_(.+)
        replacement: __param_$1
        action: labelmap
      - source_labels:
        - __meta_kubernetes_pod_label_app_kubernetes_io_part_of
        separator: ;
        regex: (.*)
        target_label: app_kubernetes_io_part_of
        replacement: $1
        action: replace
      - source_labels:
        - __meta_kubernetes_namespace
        separator: ;
        regex: (.*)
        target_label: namespace
        replacement: $1
        action: replace
      - source_labels:
        - __meta_kubernetes_pod_name
        separator: ;
        regex: (.*)
        target_label: pod
        replacement: $1
        action: replace
      - source_labels:
        - __meta_kubernetes_pod_phase
        separator: ;
        regex: Pending|Succeeded|Failed|Completed
        replacement: $1
        action: drop
      - regex: __meta_kubernetes_pod_label_app_kubernetes_io_component
        action: labeldrop
      - source_labels:
        - __meta_kubernetes_pod_label_app
        separator: ;
        regex: (.*)
        target_label: app
        replacement: $1
        action: replace
      kubernetes_sd_configs:
      - role: pod
        kubeconfig_file: ""
        follow_redirects: true
        enable_http2: true
traces:
  configs:
  - name: default
    receivers:
      zipkin: { }
      otlp:
        protocols:
          grpc:
          http:
    remote_write:
    - endpoint: tempo.tempo.svc.cluster.local:4317
      insecure: true
logs:
  configs:
  - name: default
    clients:
    - url: http://loki.loki.svc.cluster.local:3100/loki/api/v1/push
      external_labels:
        cluster: kind
    positions:
      filename: /tmp/positions.yaml
    target_config:
      sync_period: 10s
    scrape_configs:
    - job_name: pod-logs
      kubernetes_sd_configs:
      - role: pod
      pipeline_stages:
      - cri: { }
      relabel_configs:
      - source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: __host__
      #- action: labelmap
      #  regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_label_app_kubernetes_io_part_of
        target_label: app_kubernetes_io_part_of
      - action: replace
        replacement: $1
        separator: /
        source_labels:
        - __meta_kubernetes_namespace
        - __meta_kubernetes_pod_name
        target_label: job
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_uid
        - __meta_kubernetes_pod_container_name
        target_label: __path__