{
 "title": "Spring Boot Dashboard",
 "description": "Dashboard for Spring Boot Statistics",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{namespace=\"$namespace\", cluster=\"$cluster\"}, app_kubernetes_io_part_of)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\"}, pod)"
    }
   },
   {
    "name": "hikaricp",
    "label": "HikariCP-Pool",
    "query": {
     "query": "label_values(hikaricp_connections{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\"}, pool)"
    }
   },
   {
    "name": "memory_pool_heap",
    "label": "Memory Pool (heap)",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\", pod=\"$pod\", area=\"heap\"},id)"
    }
   },
   {
    "name": "memory_pool_nonheap",
    "label": "Memory Pool (nonheap)",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\", pod=\"$pod\", area=\"nonheap\"},id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Basic Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\", pod=\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\", pod=\"$pod\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\",pod=\"$pod\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\", pod=\"$pod\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\",pod=\"$pod\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Process Open Files",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "process_files_open_files{app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\", pod=\"$pod\"}",
     "legendFormat": "Open Files"
    },
    {
     "expr": "process_files_max_files{app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\", pod=\"$pod\"}",
     "legendFormat": "Max Files"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\", pod=\"$pod\"}*1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\"}",
     "legendFormat": "System CPU Usage"
    },
    {
     "expr": "process_cpu_usage{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\"}",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\"}",
     "legendFormat": "Load Average [1m]"
    },
    {
     "expr": "system_cpu_count{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\"}",
     "legendFormat": "CPU Core Size"
    }
   ]
  },
  {
   "title": "JVM Statistics - Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$memory_pool_heap (heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "repeat": "memory_pool_heap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "$memory_pool_nonheap (non-heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 23 },
   "repeat": "memory_pool_nonheap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Classes Unloaded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_classes_unloaded_classes_total{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\"}[5m])",
     "legendFormat": "Classes Unloaded"
    }
   ]
  },
  {
   "title": "Classes Loaded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\"}",
     "legendFormat": "Classes Loaded"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\", id=\"mapped\"}",
     "legendFormat": "Used Bytes"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\", id=\"mapped\"}",
     "legendFormat": "Capacity Bytes"
    }
   ]
  },
  {
   "title": "Memory Allocate/Promote",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_memory_allocated_bytes_total{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\"}[5m])",
     "legendFormat": "allocated"
    },
    {
     "expr": "irate(jvm_gc_memory_promoted_bytes_total{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\"}[5m])",
     "legendFormat": "promoted"
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\", id=\"direct\"}",
     "legendFormat": "Used Bytes"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\", id=\"direct\"}",
     "legendFormat": "Capacity Bytes"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_daemon_threads{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\"}",
     "legendFormat": "Daemon"
    },
    {
     "expr": "jvm_threads_live_threads{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\"}",
     "legendFormat": "Live"
    },
    {
     "expr": "jvm_threads_peak_threads{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\"}",
     "legendFormat": "Peak"
    }
   ]
  },
  {
   "title": "JVM Statistics - GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {}
   ]
  },
  {
   "title": "GC Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_count{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{action}} [{{cause}}]"
    }
   ]
  },
  {
   "title": "GC Stop the World Duration",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_sum{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{action}} [{{cause}}]"
    }
   ]
  },
  {
   "title": "HikariCP Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connections Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\", pool=\"$hikaricp\"}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_active{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\", pool=\"$hikaricp\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "hikaricp_connections_idle{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\", pool=\"$hikaricp\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "hikaricp_connections_pending{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\", pool=\"$hikaricp\"}",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "Connection Timeout Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections_timeout_total{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\", pool=\"$hikaricp\"}"
    }
   ]
  },
  {
   "title": "Connection Creation Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_creation_seconds_sum{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\", pool=\"$hikaricp\"} / hikaricp_connections_creation_seconds_count{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\", pool=\"$hikaricp\"}",
     "legendFormat": "Creation Time"
    }
   ]
  },
  {
   "title": "Connection Usage Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 82 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_usage_seconds_sum{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\", pool=\"$hikaricp\"} / hikaricp_connections_usage_seconds_count{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\", pool=\"$hikaricp\"}",
     "legendFormat": "Usage Time"
    }
   ]
  },
  {
   "title": "Connection Acquire Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 82 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_acquire_seconds_sum{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\", pool=\"$hikaricp\"} / hikaricp_connections_acquire_seconds_count{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\", pool=\"$hikaricp\"}",
     "legendFormat": "Acquire Time"
    }
   ]
  },
  {
   "title": "HTTP Server Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Request Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_count{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\", uri!~\".*actuator.*\"}[5m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_sum{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\", uri!~\".*actuator.*\"}[5m]) / irate(http_server_requests_seconds_count{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\", uri!~\".*actuator.*\"}[5m]) > 0",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "99 Percentile of Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\"}[3m])) by (le, method, uri, status)) > 0",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  { "title": "HTTP Client Statics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 } },
  {
   "title": "Request Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(http_client_requests_seconds_count{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 119 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(http_client_requests_seconds_sum{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\"}[5m]) / irate(http_client_requests_seconds_count{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\"}[5m]) > 0",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "99 Percentile of Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_client_requests_seconds_bucket{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\"}[3m])) by (le, method, uri, status)) > 0",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Tomcat Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 134 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Error Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tomcat_global_error_total{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Active Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 4, "y": 135 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "tomcat_sessions_active_current_sessions{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\"}",
     "legendFormat": "active sessions"
    }
   ]
  },
  {
   "title": "Sent & Recieved Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 135 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(tomcat_global_sent_bytes_total{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\"}[5m])",
     "legendFormat": "Sent Bytes"
    },
    {
     "expr": "irate(tomcat_global_received_bytes_total{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\"}[5m])",
     "legendFormat": "Recieved Bytes"
    }
   ]
  },
  {
   "title": "Thread Config Max",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tomcat_threads_config_max_threads{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 142 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_threads_current_threads{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\"}",
     "legendFormat": "Current thread"
    },
    {
     "expr": "tomcat_threads_busy_threads{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\"}",
     "legendFormat": "Current thread busy"
    }
   ]
  },
  {
   "title": "Logback Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 149 },
   "targets": [
    {}
   ]
  },
  {
   "title": "INFO logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 150 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(logback_events_total{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\", level=\"info\"}[5m])",
     "legendFormat": "info",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "ERROR logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 150 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(logback_events_total{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\", level=\"error\"}[5m])",
     "legendFormat": "error",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "WARN logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 157 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(logback_events_total{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\", level=\"warn\"}[5m])",
     "legendFormat": "warn",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "DEBUG logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 157 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(logback_events_total{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\", level=\"debug\"}[5m])",
     "legendFormat": "debug",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "TRACE logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 157 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(logback_events_total{pod=\"$pod\", app_kubernetes_io_part_of=\"$application\", namespace=\"$namespace\", cluster=\"$cluster\", level=\"trace\"}[5m])",
     "legendFormat": "trace",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  }
 ]
}