server:
  global:
    scrape_interval: 30s
  resources:
    limits:
      memory: 1Gi
  extraFlags:
  - web.enable-lifecycle
  - web.enable-remote-write-receiver
  - enable-feature=exemplar-storage
  baseURL: https://prometheus.127-0-0-1.sslip.io
  ingress:
    enabled: true
    hosts:
    - prometheus.127-0-0-1.sslip.io
    tls:
    - hosts:
      - prometheus.127-0-0-1.sslip.io
      secretName: prometheus-tls
    annotations:
      cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
serverFiles:
  prometheus.yml:
    rule_files:
    - /etc/config/recording_rules.yml
    - /etc/config/alerting_rules.yml
    scrape_configs: [ ]
alertmanager:
  enabled: false
kube-state-metrics:
  enabled: false
prometheus-node-exporter:
  enabled: false
prometheus-pushgateway:
  enabled: false